### ISSUE TITLE
Future + do you know why wizio's repo was deleted?

### ISSUE THREAD

**Issue by dmezh** [maxgerhardt/wizio-pico#1]
Hey @maxgerhardt, thanks for this backup and your recent fixes. Do you know what happened to the original repo?

ty!

**Comment by maxgerhardt** [comment]
See https://community.platformio.org/t/solved-can-not-install-https-github-com-wiz-io-wizio-pico-1-post-here-please-help/30716/14?u=maxgerhardt

![grafik](https://user-images.githubusercontent.com/26485477/230785631-0e73cb99-0f5a-4574-a979-a5057bd94322.png)

I remember him saying something about not getting support / noticed by the Raspberry Pi (foundation) people and that the SDK structure is bad, so it seems there's some bad blood now and a loss of motivation.

**Comment by caizikun** [comment]
you can try to get more latest version 1.1.1 from this site: https://gitee.com/fantj/wizio-pico

**Comment by KenwoodFox** [comment]
He said use alternatives, what would be an alternative if we were interested? 
And would it be appropriate to stick to this repo and provide further development here? Are people feeling stable about using this platform now?
